INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, cardNumberInCollection, collection_id) VALUES
(25, 'Abra', 5, 1, 'A timid Pokémon that uses its psychic power to teleport.', 'Psybeam', '10', 'Darkness', '', 1, 1, 1),
(50, 'Psyduck', 3, 1, 'Often suffers from headaches which trigger its strange powers.', 'Confusion', '20', 'Grass', '', 1, 2, 1),
(40, 'Poliwag', 3, 1, 'Tadpole-like Pokémon with a swirl on its belly.', 'Bubble', '10', 'Electric', '', 1, 3, 1),
(65, 'Poliwhirl', 3, 2, 'Can see in water with its large eyes.', 'Water Gun', '30', 'Electric', '', 2, 4, 1),
(60, 'Tentacool', 3, 1, 'Drifts in shallow seas and stings with poisonous tentacles.', 'Poison Sting', '10', 'Grass', '', 1, 5, 1),
(90, 'Tentacruel', 3, 3, 'Large and dangerous, with numerous tentacles and poison sacs.', 'Acid', '40', 'Grass', '', 2, 6, 1),
(90, 'Slowpoke', 5, 1, 'Often does silly things due to its slow reactions.', 'Yawn', '0', 'Fighting', '', 2, 7, 1),
(95, 'Slowbro', 5, 3, 'A split-second brain boost makes it strangely powerful.', 'Psychic', '40', 'Darkness', '', 2, 8, 1),
(30, 'Magnemite', 8, 1, 'Magnetic Pokémon that emits electromagnetic waves.', 'Thunder Wave', '10', 'Fighting', '', 1, 9, 1),
(60, 'Magneton', 8, 2, 'Three Magnemite clustered and magnetically linked together.', 'Magnet Bomb', '30', 'Fighting', '', 2, 10, 1),
(52, 'Farfetch''d', 11, 1, 'Carries a leek stalk which it uses as a weapon.', 'Leek Slash', '15', 'Electric', '', 1, 11, 1),
(40, 'Doduo', 11, 1, 'Two heads give it a wide field of vision.', 'Peck', '10', 'Electric', '', 1, 12, 1),
(60, 'Dodrio', 11, 3, 'Three heads coordinate to run at high speed.', 'Tri Attack', '30', 'Electric', '', 2, 13, 1),
(65, 'Seel', 3, 1, 'Smooth, white body and large eyes. Loves cold seas.', 'Headbutt', '20', 'Electric', '', 1, 14, 1),
(90, 'Dewgong', 3, 3, 'Graceful swimmer that glides through frigid waters.', 'Ice Beam', '40', 'Electric', '', 2, 15, 1),
(80, 'Grimer', 7, 1, 'Pile of sludge that oozes toxins.', 'Sludge', '20', 'Psychic', '', 1, 16, 1),
(105, 'Muk', 7, 3, 'A huge accumulation of hardened sludge.', 'Sludge Bomb', '40', 'Psychic', '', 2, 17, 1),
(30, 'Shellder', 3, 1, 'Closes its shell tightly when threatened.', 'Clamp', '10', 'Electric', '', 1, 18, 1),
(85, 'Cloyster', 3, 3, 'Armor-like shell and sharp spikes make it a fierce opponent.', 'Shell Smash', '40', 'Electric', '', 2, 19, 1),
(30, 'Krabby', 3, 1, 'Powerful pincers despite small size.', 'Vice Grip', '15', 'Grass', '', 1, 20, 1),
(100, 'Kingler', 3, 3, 'Huge pincer has tremendous crushing power.', 'Crabhammer', '50', 'Grass', '', 2, 21, 1),
(40, 'Voltorb', 4, 1, 'Looks like a Poké Ball; it is very volatile.', 'Self-Destruct', '40', 'Ground', '', 1, 22, 1),
(60, 'Electrode', 4, 3, 'Rolls at high speed and explodes on contact.', 'Explosion', '60', 'Ground', '', 2, 23, 1),
(60, 'Exeggcute', 1, 1, 'Cluster of eggs linked mentally.', 'Psychic Seed', '20', 'Fire', '', 1, 24, 1),
(95, 'Exeggutor', 1, 3, 'Tall palm-like Pokémon with three heads.', 'Solar Beam', '50', 'Fire', '', 2, 25, 1),
(50, 'Cubone', 6, 1, 'Wears the skull of its dead mother.', 'Bone Club', '20', 'Water', '', 1, 26, 1),
(85, 'Marowak', 6, 3, 'Powerful bone attacks and sturdy defense.', 'Bonemerang', '40', 'Water', '', 2, 27, 1),
(50, 'Hitmonlee', 6, 1, 'Strong legs deliver devastating kicks.', 'High Kick', '30', 'Psychic', '', 1, 28, 1),
(50, 'Hitmonchan', 6, 1, 'Learns many punch techniques.', 'Mega Punch', '30', 'Psychic', '', 1, 29, 1),
(90, 'Lickitung', 11, 1, 'Long tongue used to catch and taste things.', 'Lick', '10', 'Psychic', '', 2, 30, 1);
