INSERT INTO tbl_cards (hp, name, type_id, stage_id, info, attack, damage, weak, resist, retreat, cardNumberInCollection, collection_id) VALUES
(20, 'Magikarp', 3, 1, 'Weak and splashy, but can evolve into a powerful form.', 'Splash', '0', 'Electric', '', 1, 159, 1),
(80, 'Rhyhorn', 8, 1, 'Sturdy, rolls into foes with its heavy body.', 'Horn Attack', '30', 'Water', '', 2, 160, 1),
(105, 'Rhydon', 8, 3, 'Armor-plated and extremely strong.', 'Drill Run', '50', 'Water', '', 3, 161, 1),
(250, 'Chansey', 11, 1, 'Exceptionally kind, shares eggs to comfort others.', 'Soft-Boiled', '0', 'Fighting', '', 0, 162, 1),
(65, 'Tangela', 1, 1, 'Covered in vines that conceal its body.', 'Vine Whip', '20', 'Fire', '', 1, 163, 1),
(105, 'Kangaskhan', 11, 1, 'Motherly and powerful, protects its young in its pouch.', 'Mega Punch', '40', 'Fighting', '', 3, 164, 1),
(30, 'Horsea', 3, 1, 'Swims by rapidly flapping its small fins.', 'Bubble', '10', 'Electric', '', 1, 165, 1),
(55, 'Seadra', 3, 2, 'Fast swimmer with poisonous spines.', 'Dragon Breath', '30', 'Electric', '', 2, 166, 1),
(45, 'Goldeen', 3, 1, 'Graceful swimmer with a sharp horn.', 'Horn Attack', '15', 'Electric', '', 1, 167, 1),
(80, 'Seaking', 3, 2, 'Powerful swimmer with brutal horn strikes.', 'Drill Peck', '30', 'Electric', '', 2, 168, 1),
(30, 'Staryu', 3, 1, 'A star-shaped Pokémon that regenerates rapidly.', 'Swift', '10', 'Grass', '', 1, 169, 1),
(80, 'Starmie', 3, 3, 'Mystical core glows with unknown energy.', 'Psychic', '40', 'Grass', '', 2, 170, 1),
(60, 'Mr. Mime', 5, 1, 'Creates invisible barriers with its psychic powers.', 'Barrier', '0', 'Darkness', '', 1, 171, 1),
(70, 'Scyther', 1, 1, 'Very fast and deadly with scythe-like arms.', 'Slash', '40', 'Fire', '', 2, 172, 1),
(65, 'Jynx', 5, 1, 'Seductive movements hide a powerful psychic ability.', 'Lovely Kiss', '0', 'Fighting', '', 1, 173, 1),
(65, 'Electabuzz', 4, 1, 'Electric Pokémon that stores charge in its body.', 'Thunder Punch', '30', 'Ground', '', 2, 174, 1),
(130, 'Lapras', 3, 1, 'Gentle giant used for transport across seas.', 'Ice Beam', '50', 'Electric', '', 2, 175, 1),
(48, 'Ditto', 11, 1, 'Transforms into other Pokémon at will.', 'Transform', '0', 'Fighting', '', 1, 176, 1),
(85, 'Porygon', 11, 1, 'A man-made Pokémon that can enter cyberspace.', 'Conversion', '0', 'Electric', '', 1, 177, 1),
(160, 'Aerodactyl', 8, 3, 'Ancient flying Pokémon with razor wings.', 'Wing Attack', '50', 'Electric', '', 3, 178, 1),
(30, 'Kabuto', 8, 1, 'Fossil Pokémon with hard shell.', 'Scratch', '10', 'Water', '', 1, 179, 1),
(60, 'Kabutops', 8, 3, 'Swift and deadly with scythe-like arms.', 'Slash', '40', 'Water', '', 2, 180, 1),
(35, 'Omanyte', 8, 1, 'Small shelled fossil Pokémon revived by science.', 'Bubble Beam', '10', 'Grass', '', 1, 181, 1),
(70, 'Omastar', 8, 3, 'Spiraled shell and tentacles make it a fierce predator.', 'Hydro Pump', '50', 'Grass', '', 2, 182, 1),
(41, 'Dratini', 10, 1, 'Tiny dragon that grows stronger as it ages.', 'Dragon Breath', '10', 'Ice', '', 1, 183, 1),
(61, 'Dragonair', 10, 2, 'Graceful serpentine dragon with mystical powers.', 'Dragon Pulse', '30', 'Ice', '', 2, 184, 1),
(91, 'Dragonite', 10, 3, 'Powerful dragon Pokémon that can circle the globe in hours.', 'Hyper Beam', '70', 'Ice', '', 3, 185, 1),
(120, 'Mewtwo', 5, 3, 'A genetically engineered psychic powerhouse.', 'Psystrike', '80', 'Fighting', '', 0, 186, 1),
(100, 'Mew', 5, 1, 'Rare Pokémon said to contain the genetic codes of all Pokémon.', 'Transform', '0', 'Fighting', '', 0, 187, 1),
(70, 'Growlithe', 2, 1, 'Loyal and brave, with a fiery temperament.', 'Flame Wheel', '30', 'Water', '', 1, 188, 1);